#!/usr/bin/env python3
"""Experiment 2A: Layer-wise representational similarity analysis.

This script loads precomputed target-sentence span representations from an
NPZ archive, computes layer-wise cosine similarity and linear CKA for selected
condition pairs, adds a fixed random-sentence baseline, and optionally creates
the paper-style similarity figure.

Expected NPZ key format:
    {item_id}_{case}_L{layer}

Example:
    12_0_L16

The vectors must first be generated by
``extract_sentence_representation_for_Exp2A.py``.
"""
from __future__ import annotations
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

import argparse
import json
import re
from collections import defaultdict
from typing import Any, Iterable

import matplotlib.pyplot as plt
import numpy as np


DEFAULT_PAIRS = (("0", "1"), ("0", "2"), ("0", "4"))
DEFAULT_RANDOM_CASE = "0"
DEFAULT_RANDOM_BASELINE_NAME = "0-random"

PAIR_STYLES = {
    "0-1": {
        "marker": "o",
        "color": "red",
        "linestyle": "-",
        "label": r"$(S \mid C_{\mathrm{spec}})$ vs. $(S \mid C_{\mathrm{non}})$",
    },
    "0-2": {
        "marker": "^",
        "color": "blue",
        "linestyle": "--",
        "label": (
            r"$(S \mid C_{\mathrm{spec}})$ vs. "
            r"$(S_{\mathrm{lex}} \mid C_{\mathrm{spec}})$"
        ),
    },
    "0-4": {
        "marker": "s",
        "color": "green",
        "linestyle": ":",
        "label": (
            r"$(S \mid C_{\mathrm{spec}})$ vs. "
            r"$(S_{\mathrm{pass}} \mid C_{\mathrm{spec}})$"
        ),
    },
    "0-random": {
        "marker": "x",
        "color": "gray",
        "linestyle": "-.",
        "label": r"$(S \mid C_{\mathrm{spec}})$ vs. random sentence",
    },
}

KEY_PATTERN = re.compile(
    r"^(?P<item_id>.+)_(?P<case>[^_]+)_L(?P<layer>\d+)$"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Experiment 2A: compute layer-wise cosine similarity and linear "
            "CKA from precomputed target-sentence representations."
        )
    )
    parser.add_argument(
        "--input-vectors",
        type=Path,
        required=True,
        help="Path to the precomputed sentence_means.npz file.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory in which metrics and figures will be saved.",
    )
    parser.add_argument(
        "--pairs",
        nargs="+",
        default=["0-1", "0-2", "0-4"],
        metavar="A-B",
        help="Condition pairs to compare. Default: 0-1 0-2 0-4.",
    )
    parser.add_argument(
        "--random-case",
        default=DEFAULT_RANDOM_CASE,
        help="Condition used to construct the random-sentence baseline.",
    )
    parser.add_argument(
        "--random-baseline-name",
        default=DEFAULT_RANDOM_BASELINE_NAME,
        help="Name used for the random baseline in the output JSON.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for the random-sentence baseline.",
    )
    parser.add_argument(
        "--metrics-filename",
        default="layerwise_similarity_metrics.json",
        help="Filename for the layer-wise metric output.",
    )
    parser.add_argument(
        "--figure-filename",
        default="representation_similarity_metrics.png",
        help="Filename for the optional figure.",
    )
    parser.add_argument(
        "--skip-plot",
        action="store_true",
        help="Compute and save metrics without generating a figure.",
    )
    return parser.parse_args()


def parse_pairs(pair_strings: Iterable[str]) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for pair_string in pair_strings:
        parts = pair_string.split("-")
        if len(parts) != 2 or not all(parts):
            raise ValueError(
                f"Invalid pair '{pair_string}'. Use the format A-B, such as 0-1."
            )
        pairs.append((parts[0], parts[1]))
    return pairs


def validate_vector(vector: np.ndarray, key: str) -> np.ndarray:
    """Validate that a saved representation is a non-empty 1D vector."""
    array = np.asarray(vector)
    if array.ndim != 1:
        raise ValueError(
            f"Representation '{key}' must be one-dimensional, "
            f"but has shape {array.shape}."
        )
    if array.size == 0:
        raise ValueError(f"Representation '{key}' is empty.")
    return array


def cosine_similarity(vector_a: np.ndarray, vector_b: np.ndarray) -> float:
    """Return cosine similarity between two validated one-dimensional vectors."""
    vector_a = np.asarray(vector_a)
    vector_b = np.asarray(vector_b)

    if vector_a.ndim != 1 or vector_b.ndim != 1:
        raise ValueError("Cosine similarity expects one-dimensional vectors.")
    if vector_a.shape != vector_b.shape:
        raise ValueError(
            f"Cosine inputs must have identical shapes, got "
            f"{vector_a.shape} and {vector_b.shape}."
        )

    norm_a = np.linalg.norm(vector_a)
    norm_b = np.linalg.norm(vector_b)
    if norm_a == 0.0 or norm_b == 0.0:
        return float("nan")

    return float(np.dot(vector_a, vector_b) / (norm_a * norm_b))


def linear_cka(matrix_x: np.ndarray, matrix_y: np.ndarray) -> float:
    """Compute linear centered kernel alignment between two matrices."""
    if matrix_x.ndim != 2 or matrix_y.ndim != 2:
        raise ValueError("CKA expects two-dimensional matrices.")
    if matrix_x.shape[0] < 2 or matrix_y.shape[0] < 2:
        return float("nan")
    if matrix_x.shape != matrix_y.shape:
        raise ValueError(
            f"CKA inputs must have identical shapes, got "
            f"{matrix_x.shape} and {matrix_y.shape}."
        )

    centered_x = matrix_x - matrix_x.mean(axis=0, keepdims=True)
    centered_y = matrix_y - matrix_y.mean(axis=0, keepdims=True)

    cross_term = np.linalg.norm(centered_x.T @ centered_y, ord="fro") ** 2
    x_term = np.linalg.norm(centered_x.T @ centered_x, ord="fro") ** 2
    y_term = np.linalg.norm(centered_y.T @ centered_y, ord="fro") ** 2

    if x_term == 0.0 or y_term == 0.0:
        return float("nan")

    return float(cross_term / np.sqrt(x_term * y_term))


def load_representations(
    input_path: Path,
) -> tuple[dict[str, dict[str, dict[int, np.ndarray]]], list[int]]:
    """Load NPZ vectors into item -> case -> layer -> vector structure."""
    if not input_path.is_file():
        raise FileNotFoundError(f"Representation file not found: {input_path}")

    archive = np.load(input_path, allow_pickle=False)
    representations: dict[str, dict[str, dict[int, np.ndarray]]] = defaultdict(
        lambda: defaultdict(dict)
    )
    layers: set[int] = set()

    invalid_keys: list[str] = []
    for key in archive.files:
        match = KEY_PATTERN.match(key)
        if match is None:
            invalid_keys.append(key)
            continue

        item_id = match.group("item_id")
        case = match.group("case")
        layer = int(match.group("layer"))
        vector = validate_vector(archive[key], key)

        representations[item_id][case][layer] = vector
        layers.add(layer)

    archive.close()

    if invalid_keys:
        examples = ", ".join(invalid_keys[:5])
        raise ValueError(
            "Some NPZ keys do not follow the expected "
            f"'{{item_id}}_{{case}}_L{{layer}}' format: {examples}"
        )

    if not representations:
        raise ValueError(f"No valid representations were found in {input_path}.")

    return representations, sorted(layers)


def compute_pair_metrics(
    representations: dict[str, dict[str, dict[int, np.ndarray]]],
    layers: Iterable[int],
    case_a: str,
    case_b: str,
) -> dict[int, dict[str, float | int]]:
    """Compute layer-wise metrics for aligned items from two conditions."""
    layer_results: dict[int, dict[str, float | int]] = {}

    for layer in layers:
        vectors_a: list[np.ndarray] = []
        vectors_b: list[np.ndarray] = []

        for case_map in representations.values():
            vector_a = case_map.get(case_a, {}).get(layer)
            vector_b = case_map.get(case_b, {}).get(layer)
            if vector_a is None or vector_b is None:
                continue

            vectors_a.append(vector_a)
            vectors_b.append(vector_b)

        if not vectors_a:
            layer_results[layer] = {
                "cosine": float("nan"),
                "cka": float("nan"),
                "n": 0,
            }
            continue

        if len(vectors_a) != len(vectors_b):
            raise RuntimeError(
                f"Mismatched pair counts for cases {case_a} and {case_b} "
                f"at layer {layer}."
            )

        matrix_a = np.stack(vectors_a, axis=0)
        matrix_b = np.stack(vectors_b, axis=0)

        cosine_values = [
            cosine_similarity(vector_a, vector_b)
            for vector_a, vector_b in zip(matrix_a, matrix_b)
        ]

        layer_results[layer] = {
            "cosine": float(np.nanmean(cosine_values)),
            "cka": linear_cka(matrix_a, matrix_b),
            "n": int(matrix_a.shape[0]),
        }

    return layer_results


def build_fixed_random_pairing(
    representations: dict[str, dict[str, dict[int, np.ndarray]]],
    random_case: str,
    seed: int,
) -> dict[str, str]:
    """Create one deranged item pairing that is reused across all layers."""
    eligible_item_ids = sorted(
        item_id
        for item_id, case_map in representations.items()
        if random_case in case_map
    )

    if len(eligible_item_ids) < 2:
        return {}

    rng = np.random.default_rng(seed)
    source_ids = np.asarray(eligible_item_ids, dtype=object)

    for _ in range(10_000):
        target_ids = source_ids.copy()
        rng.shuffle(target_ids)
        if np.all(source_ids != target_ids):
            return {
                str(source_id): str(target_id)
                for source_id, target_id in zip(source_ids, target_ids)
            }

    raise RuntimeError(
        "Could not construct a fixed random pairing without self-pairs."
    )


def compute_random_baseline(
    representations: dict[str, dict[str, dict[int, np.ndarray]]],
    layers: Iterable[int],
    random_case: str,
    seed: int,
) -> dict[int, dict[str, float | int]]:
    """Compare each item with the same randomly paired item at every layer."""
    layer_results: dict[int, dict[str, float | int]] = {}
    fixed_pairing = build_fixed_random_pairing(
        representations,
        random_case,
        seed,
    )

    for layer in layers:
        vectors_a: list[np.ndarray] = []
        vectors_b: list[np.ndarray] = []

        for item_id, random_item_id in fixed_pairing.items():
            vector_a = (
                representations.get(item_id, {})
                .get(random_case, {})
                .get(layer)
            )
            vector_b = (
                representations.get(random_item_id, {})
                .get(random_case, {})
                .get(layer)
            )
            if vector_a is None or vector_b is None:
                continue

            vectors_a.append(vector_a)
            vectors_b.append(vector_b)

        if len(vectors_a) < 2:
            layer_results[layer] = {
                "cosine": float("nan"),
                "cka": float("nan"),
                "n": len(vectors_a),
            }
            continue

        matrix_a = np.stack(vectors_a, axis=0)
        matrix_b = np.stack(vectors_b, axis=0)
        cosine_values = [
            cosine_similarity(vector_a, vector_b)
            for vector_a, vector_b in zip(matrix_a, matrix_b)
        ]

        layer_results[layer] = {
            "cosine": float(np.nanmean(cosine_values)),
            "cka": linear_cka(matrix_a, matrix_b),
            "n": int(matrix_a.shape[0]),
        }

    return layer_results


def json_safe(value: Any) -> Any:
    """Convert NumPy and non-finite values into JSON-compatible objects."""
    if isinstance(value, dict):
        return {str(key): json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, np.generic):
        value = value.item()
    if isinstance(value, float) and not np.isfinite(value):
        return None
    return value


def save_metrics(
    metrics: dict[str, dict[int, dict[str, float | int]]],
    output_path: Path,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as output_file:
        json.dump(
            json_safe(metrics),
            output_file,
            indent=2,
            ensure_ascii=False,
        )


def get_metric(
    metrics: dict[str, dict[int, dict[str, float | int]]],
    pair_name: str,
    layer: int,
    metric_name: str,
) -> float:
    value = metrics.get(pair_name, {}).get(layer, {}).get(metric_name)
    return float("nan") if value is None else float(value)


def piecewise_axis_functions(
    y_min: float = 0.20,
    y_split: float = 0.75,
    y_max: float = 1.01,
    lower_to_upper_height_ratio: float = 0.25,
):
    """Create forward and inverse transforms for the paper-style y-axis."""
    lower_range = y_split - y_min
    upper_range = y_max - y_split
    compression = lower_to_upper_height_ratio * upper_range / lower_range
    transformed_split = compression * lower_range

    def forward(values):
        values = np.asarray(values, dtype=float)
        return np.where(
            values <= y_split,
            compression * (values - y_min),
            transformed_split + (values - y_split),
        )

    def inverse(values):
        values = np.asarray(values, dtype=float)
        return np.where(
            values <= transformed_split,
            y_min + values / compression,
            y_split + (values - transformed_split),
        )

    return forward, inverse


def plot_metrics(
    metrics: dict[str, dict[int, dict[str, float | int]]],
    layers: list[int],
    output_path: Path,
) -> None:
    """Create the two-panel cosine and CKA figure used for reporting."""
    figure, axes = plt.subplots(1, 2, figsize=(12, 4), sharex=True)
    metric_specs = (
        ("cosine", "Cosine Similarity", "Cosine"),
        ("cka", "CKA", "CKA"),
    )
    forward, inverse = piecewise_axis_functions()
    y_ticks = [0.20, 0.40, 0.60, 0.75, 0.80, 0.85, 0.90, 0.95, 1.00]

    for axis, (metric_name, title, ylabel) in zip(axes, metric_specs):
        for pair_name in metrics:
            style = PAIR_STYLES.get(
                pair_name,
                {
                    "marker": "o",
                    "linestyle": "-",
                    "label": pair_name,
                },
            )
            values = [
                get_metric(metrics, pair_name, layer, metric_name)
                for layer in layers
            ]

            axis.plot(
                layers,
                values,
                label=style["label"],
                marker=style["marker"],
                color=style.get("color"),
                linestyle=style["linestyle"],
                linewidth=2,
                markersize=5,
            )

        axis.set_yscale("function", functions=(forward, inverse))
        axis.set_ylim(0.20, 1.01)
        axis.set_yticks(y_ticks)
        axis.set_yticklabels([f"{tick:.2f}" for tick in y_ticks])
        axis.set_title(title, fontsize=16)
        axis.set_xlabel("Layer", fontsize=12)
        axis.set_ylabel(ylabel, fontsize=12)
        axis.grid(True, alpha=0.3)
        axis.legend(fontsize=9, frameon=True, loc="best")

    figure.suptitle(
        "Experiment 2A: Layer-wise Representation Similarity",
        fontsize=18,
    )
    figure.tight_layout(rect=[0, 0.0, 1, 0.93])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def main() -> None:
    args = parse_args()
    pairs = parse_pairs(args.pairs)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    representations, layers = load_representations(args.input_vectors)

    metrics: dict[str, dict[int, dict[str, float | int]]] = {}
    for case_a, case_b in pairs:
        pair_name = f"{case_a}-{case_b}"
        metrics[pair_name] = compute_pair_metrics(
            representations,
            layers,
            case_a,
            case_b,
        )

    metrics[args.random_baseline_name] = compute_random_baseline(
        representations,
        layers,
        args.random_case,
        args.seed,
    )

    metrics_path = args.output_dir / args.metrics_filename
    save_metrics(metrics, metrics_path)

    print(f"Loaded representations from: {args.input_vectors}")
    print(f"Detected layers: {layers}")
    print(f"Saved metrics to: {metrics_path}")

    if not args.skip_plot:
        figure_path = args.output_dir / args.figure_filename
        plot_metrics(metrics, layers, figure_path)
        print(f"Saved figure to: {figure_path}")


if __name__ == "__main__":
    main()
